name: Continuous deployment

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          NETLIFY_WEBHOOK: ${{ secrets.NETLIFY_WEBHOOK }}
        run: |
          curl -X POST -d {} "$NETLIFY_WEBHOOK"
