name: Scheduled build
on:
  schedule:
    - cron: '00 03 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        run: curl -s -X POST ${{ secrets.NETLIFY_WEBHOOK_URL }}
